### ISSUE TITLE
solutions of questions

### ISSUE THREAD

**Issue by akrsnr** [Apress/java-language-features#1]
I can't see solutions of the questions. There aren't answers in `Solution_to_Exercises.zip`, for example for chapter 5. Not compatible!

**Comment by MarkP88** [comment]
Hi, 

I just downloaded and opened the .zip; all the answers are there, including Chapter 5. There are 12 PDF documents, each containing the answers for a single chapter. Here is Chapter 5, for example.

Can you please look again?

Best,
Mark Powers
[Ch05_JDBC_API.pdf](https://github.com/Apress/java-language-features/files/2280429/Ch05_JDBC_API.pdf)

**Comment by akrsnr** [comment]
Yes, the issue is that Chapter 5 mentions `Lambda Expressions`, not JDBC.

**Comment by kishorisharan** [comment]
Hello Mark, 
I see the problem. We had the "solutions" from the third volume "Java APIs, Extensions and Libraries" uploaded to this project, which is for the second volume "Java Language Features". I have uploaded the correct version of the file. 

Please try to download the file again.  

Thanks
Kishori

**Comment by MarkP88** [comment]
Thank you very much, Kishori.

Best,
Mark
